"""NestJS extractor for `quantpilot-frontend/apps/api`.

Strategy: parse *.controller.ts files with regex (not TS AST — we keep the
skill zero-dependency). NestJS routing is declarative enough that this stays
deterministic: each controller has `@Controller('base')`, each handler method
has an `@Get/@Post/@Put/@Patch/@Delete('suffix')` decorator, and auth is
expressed through `@UseGuards(...)` at class- or method-level.

We cross-check against `apps/api/openapi.json` (generated by NestJS Swagger)
to catch cases the regex misses; the openapi.json is the source-of-truth
path list, and the source scan fills in the auth level + guard evidence.
"""
from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SCRIPT_DIR))
from models import Auth, EndpointRow  # noqa: E402

REPOSITORY = "frontend-api"
GLOBAL_PREFIX = "/api"
GLOBAL_PREFIX_EXCLUDED = {"/health"}

_DECORATOR_NAMES = ("Controller", "Get", "Post", "Put", "Patch", "Delete", "UseGuards", "SkipSsoAuthorization", "ApiTags")
_DECORATOR_START_RE = re.compile(
    r"@(" + "|".join(_DECORATOR_NAMES) + r")\b(\s*\()?",
)
_CLASS_RE = re.compile(r"^\s*export\s+class\s+(\w+)\b", re.MULTILINE)


def _find_decorators(text: str) -> list[tuple[int, str, str]]:
    """Return list of (offset, decorator_name, args_inside_parens).

    Handles nested parens (e.g. @UseGuards(AuthGuard('jwt'))).
    """
    out: list[tuple[int, str, str]] = []
    for m in _DECORATOR_START_RE.finditer(text):
        name = m.group(1)
        open_paren_idx = m.end(1)
        # Skip any whitespace between name and '('.
        i = open_paren_idx
        while i < len(text) and text[i].isspace():
            i += 1
        if i >= len(text) or text[i] != "(":
            # Decorator without parens like @SkipSsoAuthorization
            out.append((m.start(), name, ""))
            continue
        # Find matching close paren.
        depth = 0
        j = i
        start_arg = i + 1
        in_str: str | None = None  # the quote character we're inside, or None
        escape = False
        while j < len(text):
            c = text[j]
            if in_str:
                if escape:
                    escape = False
                elif c == "\\":
                    escape = True
                elif c == in_str:
                    in_str = None
                j += 1
                continue
            if c in ("'", '"', "`"):
                in_str = c
                j += 1
                continue
            if c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    out.append((m.start(), name, text[start_arg:j]))
                    break
            j += 1
    return out


@dataclass
class _HandlerDecl:
    method: str  # GET / POST / ...
    path_suffix: str
    line: int
    guards: list[str] = field(default_factory=list)
    skip_sso: bool = False


def extract(repo_root: Path) -> tuple[list[EndpointRow], list[str]]:
    warnings: list[str] = []
    api_root = repo_root / "apps" / "api"
    if not api_root.exists():
        warnings.append("apps/api not found — not a frontend repo?")
        return [], warnings

    # Load openapi.json if available (authoritative path list).
    openapi_file = api_root / "openapi.json"
    openapi_paths: dict[tuple[str, str], str] = {}  # (path, METHOD) -> operationId
    if openapi_file.exists():
        try:
            openapi = json.loads(openapi_file.read_text())
            for path, ops in openapi.get("paths", {}).items():
                for verb, op in ops.items():
                    if verb.lower() in ("get", "post", "put", "patch", "delete"):
                        openapi_paths[(path, verb.upper())] = op.get("operationId", "")
        except Exception as exc:
            warnings.append(f"failed to parse openapi.json: {exc!r}")
    else:
        warnings.append(
            "apps/api/openapi.json not found — run `npm run openapi:generate` in apps/api/ "
            "for best path coverage; falling back to controller source scan only."
        )

    rows_by_key: dict[tuple[str, str], EndpointRow] = {}

    # Scan every *.controller.ts.
    for controller in sorted((api_root / "src").rglob("*.controller.ts")):
        if controller.suffix != ".ts" or controller.name.endswith(".spec.ts"):
            continue
        try:
            text = controller.read_text()
        except OSError:
            continue
        for base_path, class_guards, class_skip_sso, handlers in _parse_controller(text):
            rel_file = controller.relative_to(repo_root)
            for h in handlers:
                effective_guards = h.guards or class_guards
                skip_sso = class_skip_sso or h.skip_sso
                full_path = _compose_full_path(base_path, h.path_suffix)
                auth, _guard_str = _classify(effective_guards, full_path, skip_sso)
                row = EndpointRow(
                    repository=REPOSITORY,
                    method=h.method,
                    path=full_path,
                    auth=auth,
                    source_kind="NestJS",
                )
                rows_by_key[(full_path, h.method)] = row

    # Merge openapi.json paths we didn't find in source (possible dynamic decorators).
    for key, op_id in openapi_paths.items():
        if key in rows_by_key:
            continue
        full_path, method = key
        rows_by_key[key] = EndpointRow(
            repository=REPOSITORY,
            method=method,
            path=full_path,
            auth=Auth.UNSPECIFIED,
            source_kind="NestJS (openapi.json only)",
        )
        warnings.append(f"openapi.json lists {method} {full_path} but no controller was matched")

    # Report paths found in source but missing from openapi.json — indicates stale openapi.
    if openapi_paths:
        missing_from_oa = [key for key in rows_by_key if key not in openapi_paths]
        if missing_from_oa:
            warnings.append(
                f"{len(missing_from_oa)} path(s) found in source but not in openapi.json — "
                "consider re-running `npm run openapi:generate` in apps/api/"
            )

    return list(rows_by_key.values()), warnings


def _parse_controller(text: str):
    """Yield (base_path, class_guards, class_skip_sso, handlers) tuples per controller class."""
    decorators = _find_decorators(text)  # list of (offset, name, args)
    class_positions = [(m.start(), m.group(1)) for m in _CLASS_RE.finditer(text)]
    if not class_positions:
        return
    class_positions.append((len(text), ""))  # sentinel

    for i in range(len(class_positions) - 1):
        class_start, _ = class_positions[i]
        class_end, _ = class_positions[i + 1]

        # Class decorators: contiguous run of decorators whose end paren is just before the class line.
        # Practically: all decorators whose offset is < class_start AND > previous-class-end (or 0).
        prev_end = class_positions[i - 1][0] if i > 0 else 0
        class_decs = [d for d in decorators if prev_end < d[0] < class_start]
        # Method decorators live between class_start (brace) and class_end.
        method_decs = [d for d in decorators if class_start < d[0] < class_end]

        base_path = ""
        class_guards: list[str] = []
        class_skip_sso = False
        for _off, name, arg in class_decs:
            if name == "Controller":
                base_path = _string_literal(arg) or ""
            elif name == "UseGuards":
                class_guards.extend(_extract_guard_names(arg))
            elif name == "SkipSsoAuthorization":
                class_skip_sso = True

        handlers = _parse_handlers(method_decs, text)
        yield base_path, class_guards, class_skip_sso, handlers


def _parse_handlers(decorators: list[tuple[int, str, str]], text: str) -> list[_HandlerDecl]:
    """From the method-level decorators, group them into handlers by proximity.

    A handler = consecutive run of decorators (possibly separated by blank lines / comments)
    immediately followed by a method signature, where at least one of the decorators is a
    HTTP verb (@Get, @Post, …).
    """
    # Sort by offset and group contiguous decorators.
    decorators.sort(key=lambda d: d[0])
    handlers: list[_HandlerDecl] = []
    i = 0
    while i < len(decorators):
        group = [decorators[i]]
        j = i + 1
        while j < len(decorators):
            # If the text between the previous decorator's end and this decorator's start
            # contains only whitespace and comments, treat them as the same group.
            prev = decorators[j - 1]
            _off, _name, prev_arg = prev
            prev_end_approx = prev[0]  # we only know the start offset; approximate end by args length
            prev_end_approx += len("@" + prev[1]) + (len(prev[2]) + 2 if prev[2] else 0)
            # But prev_end might undercount due to whitespace; use next start and trust the gap check.
            gap = text[prev_end_approx:decorators[j][0]]
            # If gap contains non-comment, non-whitespace code, break.
            if _contains_real_code(gap):
                break
            group.append(decorators[j])
            j += 1
        # Emit handler if group has a verb decorator.
        verb = None
        path_suffix = ""
        guards: list[str] = []
        skip_sso = False
        first_verb_offset = None
        for off, name, arg in group:
            if name in ("Get", "Post", "Put", "Patch", "Delete"):
                verb = name.upper()
                path_suffix = _string_literal(arg) or ""
                first_verb_offset = off
            elif name == "UseGuards":
                guards.extend(_extract_guard_names(arg))
            elif name == "SkipSsoAuthorization":
                skip_sso = True
        if verb is not None and first_verb_offset is not None:
            line = text[:first_verb_offset].count("\n") + 1
            handlers.append(
                _HandlerDecl(
                    method=verb,
                    path_suffix=path_suffix,
                    line=line,
                    guards=guards,
                    skip_sso=skip_sso,
                )
            )
        i = j
    return handlers


def _contains_real_code(gap: str) -> bool:
    """True if `gap` contains non-whitespace code outside of single-line or block comments."""
    if not gap.strip():
        return False
    # Strip block comments /* ... */
    without_block = re.sub(r"/\*.*?\*/", "", gap, flags=re.DOTALL)
    # Strip line comments // ... \n
    without_line = re.sub(r"//[^\n]*", "", without_block)
    return bool(without_line.strip())


def _string_literal(arg: str) -> str | None:
    # Accept single-quoted or double-quoted first token.
    s = arg.strip()
    if not s:
        return ""
    # Strip leading object-like args (rare): e.g. `'foo', { version: '1' }` → 'foo'.
    m = re.match(r"""^\s*(['"`])([^'"`]*?)\1""", s)
    if m:
        return m.group(2)
    return None


def _extract_guard_names(arg: str) -> list[str]:
    """From `@UseGuards(A, B('jwt'), C)` extract ['A', "B('jwt')", 'C']."""
    # Split by top-level commas.
    out: list[str] = []
    depth = 0
    current = []
    for ch in arg:
        if ch in "([{":
            depth += 1
            current.append(ch)
        elif ch in ")]}":
            depth -= 1
            current.append(ch)
        elif ch == "," and depth == 0:
            val = "".join(current).strip()
            if val:
                out.append(val)
            current = []
        else:
            current.append(ch)
    tail = "".join(current).strip()
    if tail:
        out.append(tail)
    return out


def _compose_full_path(base_path: str, suffix: str) -> str:
    base = base_path.strip("/")
    suf = suffix.strip("/")
    joined = "/".join(p for p in [base, suf] if p)
    raw = "/" + joined if joined else "/"
    # Normalize: drop trailing slash (except root), collapse double slashes.
    raw = re.sub(r"/+", "/", raw)
    if len(raw) > 1 and raw.endswith("/"):
        raw = raw[:-1]
    # Match NestJS path-param syntax to OpenAPI: :param → {param}.
    raw = re.sub(r":([A-Za-z_][\w]*)", r"{\1}", raw)
    # Apply global prefix unless excluded.
    if raw in GLOBAL_PREFIX_EXCLUDED:
        return raw
    return GLOBAL_PREFIX + raw if raw != "/" else GLOBAL_PREFIX


def _classify(guards: list[str], full_path: str, skip_sso: bool) -> tuple[str, str]:
    webhook_paths = ("/api/stripe/webhook", "/api/anthropic-status/webhook")
    if full_path in webhook_paths:
        return Auth.SIGNATURE, "webhook signature check in handler"
    if not guards:
        return Auth.PUBLIC, ""
    text = ", ".join(guards)
    low = text.lower()
    if "okta" in low:
        return Auth.OKTA, text
    if "agenticapikey" in low or "landingapikey" in low or "serviceapikey" in low or "apikey" in low:
        return Auth.API_KEY, text
    if "'jwt'" in low or '"jwt"' in low or "jwtauthguard" in low or "authguard('jwt')" in low:
        return Auth.JWT, text
    # Unrecognized guard — record the name but fall back to jwt (the default NestJS pattern).
    return Auth.JWT, text
